# Generated by Django 6.0 on 2025-12-29 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationchannel'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationevent'),
        ),
    ]
